### ISSUE TITLE
Packages don't get synced

### ISSUE THREAD

**Issue by Dhq** [atom-community/sync-settings#137]
With the risk of me misunderstanding something, I can't get my packages to sync. I went through the following scenario:
1. I install new packages on Machine 1 and upload the settings through the "Sync Backup" command in atom. I can see that the new packages are listed in the packages.json file in the gist.
2. On Machine 2 I restore the settings and can indeed see settings being restored, like keymaps. However I don't get my new packages. I have restarted and reloaded Atom without luck.

Are there any extra steps I need to take to get the new packages on Machine 2?

**Comment by brego** [comment]
:+1: 

I'm experiencing the same issue.

**Comment by vassyz** [comment]
Check what's in your ```~/.atom/packages``` folder. I had to restart Atom a couple of times to get the packages installed. It doesn't seem to sync the disabled packages though.

**Comment by johannes-z** [comment]
+1

**Comment by cristobal-io** [comment]
+1

**Comment by avances123** [comment]
+1

**Comment by cmark** [comment]
+1

**Comment by smshuja** [comment]
Restore doesn't work for me too

**Comment by frozeus** [comment]
Same issue.
Remove the .atom folder, installed sync-settings, setup up my github token + gist id -> then sync-settings restore.

```
sync-settings.coffee:80 checking latest backup...
sync-settings.coffee:243 Creating GitHubApi client with token = XXXXX
tracker.coffee:54 tracking Activate
/opt/atom/resources/app.asar/node_modules/settings-view/lib/main.js:138 Fetching local packages failed. Error: Fetching local packages failed.
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:103:21
    at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
sync-settings.coffee:84 null Object
sync-settings.coffee:95 latest backup version dcfeacff3e9f1efcd948cdbfd206cc74bf80186b
```

**Comment by frozeus** [comment]
More usefull debug when calling sync-settings restore
```
latest backup version dcfeacff3e9f1efcd948cdbfd206cc74bf80186b
sync-settings.coffee:243 Creating GitHubApi client with token = XXXXX
tracker.coffee:54 tracking Restore
sync-settings.coffee:300 Installing package atom-ctags...
sync-settings.coffee:300 Installing package autocomplete-ctags...
sync-settings.coffee:300 Installing package editorconfig...
sync-settings.coffee:300 Installing package highlight-selected...
sync-settings.coffee:300 Installing package minimap...
sync-settings.coffee:300 Installing package minimap-highlight-selected...
sync-settings.coffee:300 Installing theme monokai-seti...
sync-settings.coffee:300 Installing package project-manager...
sync-settings.coffee:300 Installing theme seti-ui...
sync-settings.coffee:300 Installing package todo-show...
sync-settings.coffee:285 config.set autocomplete-ctags.disableBuiltinProvider=true
sync-settings.coffee:285 config.set core.disabledPackages=symbols-view
sync-settings.coffee:285 config.set core.themes=seti-ui,monokai-seti
sync-settings.coffee:285 config.set editor.fontSize=12
sync-settings.coffee:285 config.set exception-reporting.userId=357e766f-4c69-abb3-cdef-05eed8ecbf09
sync-settings.coffee:285 config.set minimap.plugins.highlight-selected=true
sync-settings.coffee:285 config.set minimap.plugins.highlight-selectedDecorationsZIndex=0
sync-settings.coffee:285 config.set tree-view.hideVcsIgnoredFiles=true
sync-settings.coffee:285 config.set welcome.showOnStartup=false
sync-settings.coffee:304 Installing package todo-show failed Error: Installing “todo-show@1.3.0” failed.
    at /home/clement/.atom/packages/sync-settings/lib/package-manager.coffee:172:21
    at exit (/home/clement/.atom/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) /opt/atom/resources/app/apm/bin/apm: line 27: cd: (unreachable)/: No such file or directory
(anonymous function) @ sync-settings.coffee:304(anonymous function) @ package-manager.coffee:177exit @ package-manager.coffee:27triggerExitCallback @ /opt/atom/resources/app.asar/src/buffered-process.js:213(anonymous function) @ /opt/atom/resources/app.asar/src/buffered-process.js:220(anonymous function) @ /opt/atom/resources/app.asar/src/buffered-process.js:98emitOne @ events.js:82emit @ events.js:169(anonymous function) @ net.js:469
sync-settings.coffee:304 Installing theme seti-ui failed Error: Installing “seti-ui@0.9.1” failed.
    at /home/clement/.atom/packages/sync-settings/lib/package-manager.coffee:172:21
    at exit (/home/clement/.atom/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) /opt/atom/resources/app/apm/bin/apm: line 27: cd: (unreachable)/: No such file or directory
```

**Comment by H5DevHoward** [comment]
same issue here

**Comment by jon-freed** [comment]
Same issue.

I manually found a package that was missing ("script").  I tried to install it manually on the destination machine and got this:  "Failed to install script because Git was not found."

I installed Git and then tried to do a sync again.  Still no "script".  I closed Atom and then restarted it, and the missing package showed up.

Perhaps sync-settings should monitor the installation of packages that it initiates and then tell the user about any installation error messages.

**Comment by sveggiani** [comment]
+1

**Comment by marx-freedom** [comment]
Same issue, but only with a packages installed from git repos.

on machine1 
- apm install https://github.com/saltstack/atom-salt
- backup configuration

on machine2
- restore configuration
- atom-salt package was not installed

packages.json in my gist contains these lines

```
	{
		"name": "atom-salt",
		"version": "0.3.0"
	},
```

**Comment by Beatris** [comment]
I experienced the same issue. In my case, the problem was that apm hadn't the permissions to install packages without sudo. So:
`sudo chown -R 777 ~/.atom/packages/`
But I absolutely agree with @jon-freed 's statement that "sync-settings should monitor the installation of packages that it initiates and then tell the user about any installation error messages".

**Comment by ali-hellani** [comment]
+1

**Comment by dirk-thomas** [comment]
PR #311 adds notifications to keep the user informed about the progress of installing packages.

**Comment by cassioKenji** [comment]
+1

**Comment by dirk-thomas** [comment]
I will close this for now since it has been a while since the notifications have been added which provide detailed feedback about the progress of installing packages as well as eventual failures. Please feel free to comment if there a still problems and describe the process as detailed as possible.
