### ISSUE TITLE
Uncaught TypeError: Cannot read property 'track' of undefined

### ISSUE THREAD

**Issue by BrandonShega** [atom-community/sync-settings#155]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'track' of undefined

```
At /C:/Users/bsheg/.atom/packages/sync-settings/lib/sync-settings.coffee:33

TypeError: Cannot read property 'track' of undefined
    at atom-workspace.<anonymous> (file:///C:/Users/bsheg/.atom/packages/sync-settings/lib/sync-settings.coffee:24:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\bsheg\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:53.6.0 sync-settings:view-backup (atom-text-editor.editor.vim-mode.normal-mode)
     -0:49.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:47.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44 sync-settings:restore (atom-text-editor.editor.vim-mode.normal-mode)
     -0:11.1.0 project-manager:list-projects (atom-text-editor.editor.mini.is-focused)
     -0:09.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
     -0:07.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
     -0:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.9.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "jslint"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "1419fdfd-5786-4cfe-92a0-d113bba553f5",
    "gistId": "81a5b3dd980d0e853f42",
    "extraFiles": [
      "aa76e578e8506d5377d35b4ea26780e98397f2d2"
    ],
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "_lastBackupHash": "bcc709370f79341809bbdd16668d06afed2e6f53"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
autoclose-html, v0.19.0
docblockr, v0.7.3
emmet, v2.3.15
file-icons, v1.6.12
indent-guide-improved, v1.4.4
jshint, v1.8.3
linter, v1.11.2
markdown-preview-plus, v2.2.2
minimap, v4.16.2
php-debug, v0.1.4
pigments, v0.19.0
project-manager, v2.6.5
sync-settings, v0.6.0
vim-mode, v0.63.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
This my be responsible for the problem: https://github.com/Hackafe/atom-sync-settings/pull/88/files#r49615887

Lets wait what the author of that snippet has to say.

**Comment by dirk-thomas** [comment]
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by jerone** [comment]
Closing as this issue has been stale for 3 months.

**Comment by rpavlik** [comment]
This is still happening - debian jessie, latest Atom official build, and apparently latest plugin version. As far as I can tell, I can't sync settings anymore to this system.
