### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/thr3a/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by thr3a** [atom-community/sync-settings#241]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/thr3a/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/thr3a/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/thr3a/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/thr3a/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/thr3a/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/Users/thr3a/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/Users/thr3a/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -8:15.2.0 terminal-plus:copy (div.terminal)
     -8:13.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -8:12.7.0 core:paste (atom-text-editor.editor.is-focused)
     -6:31 core:copy (atom-text-editor.editor.is-focused)
     -1:49 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:43.3.0 sync-settings:backup (div.panels-item)
     -0:11.5.0 sync-settings:view-backup (input#sync-settings.analytics.)
     -0:00.9.0 sync-settings:backup (input#sync-settings.analytics.)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "e3fa7592-38a1-4e0b-be2d-ef27a0e3ed85",
    "_lastBackupHash": "12822aa742b6f5cf360bf842b0e55534131cf3de",
    "analytics": false,
    "gistId": "6a32c2fae25821aacf6e",
    "personalAccessToken": "e72ea7d830839d807865932f2d5926bc10c91fb3"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
file-icons, v1.6.18
highlight-selected, v0.11.2
japanese-menu, v1.6.2
language-slim, v0.5.0
remote-sync, v3.5.0
show-ideographic-space, v1.0.1
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
tag, v0.3.0
term3, v0.21.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jerone** [comment]
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
