### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/michaelwu/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by michael-yx-wu** [atom-community/sync-settings#243]
[Enter steps to reproduce below:]

1. Occurred when trying to backup atom settings

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/michaelwu/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/michaelwu/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/michaelwu/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/michaelwu/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/michaelwu/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/Users/michaelwu/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/Users/michaelwu/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -1:29.3.0 core:undo (atom-text-editor.editor.is-focused)
     -1:28 core:save (atom-text-editor.editor.is-focused)
     -1:24.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -1:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.3.0 core:cancel (a.btn-issue.btn.btn-error)
     -0:25.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:25.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:24.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.5.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  2x -0:24.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:23.7.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:05.0 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.5.0 command-palette:toggle (div.panels-item)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 sync-settings:backup (div.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "linter-pep8"
    ],
    "packagesWithKeymapsDisabled": [
      "rst-preview"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "f5dadac4-f1ce-4e55-9cec-2ccd78267148",
    "_lastBackupHash": "7660158cf51262f927577b2984d01fc17f539af1",
    "gistId": "bce6696888498e38f5a1",
    "personalAccessToken": "415a166fa22fd2427bc530b1971a7c9bcb0f4ad2"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.3.0
autocomplete-python, v1.7.0
language-docker, v1.1.6
language-gradle, v0.0.3
language-groovy, v0.5.0
language-restructuredtext, v0.12.0
linter, v1.11.3
linter-clang, v3.4.4
linter-javac, v1.8.1
linter-ruby, v1.2.2
linter-shellcheck, v1.1.0
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
omni-ruler, v0.4.2
rest-client, v0.5.1
rst-preview-pandoc, v0.1.12
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by michael-yx-wu** [comment]
Closing in favor of #194

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by michael-yx-wu** [comment]
I don't think so? It seems like it's redacted with `xxxx`

**Comment by dirk-thomas** [comment]
I replaced the `personAccessToken` with a placeholder in you post to prevent people scraping the tickets for such information. But you should still consider the token to be compromised.

**Comment by michael-yx-wu** [comment]
Oh I see. Thanks! Is there a way for atom to auto redact it?

**Comment by dirk-thomas** [comment]
Sadly there is no such way.
