### ISSUE TITLE
Restore of packages fails silently if a package version does not exist (anymore)

### ISSUE THREAD

**Issue by 5nafu** [atom-community/sync-settings#266]
I had the package seti-ui installed with version 0.9.2:

```
{
    "name": "seti-ui",
    "version": "0.9.2",
    "theme": "ui"
},
```

The restore succeeds, but (at least) this package is not installed. In the developer console, one can see the message

```
Installing theme seti-ui failed Error: Installing “seti-ui@0.9.2” failed.
    at /data/home/tvollmer/.atom/packages/sync-settings/lib/package-manager.coffee:172:21
    at exit (/data/home/tvollmer/.atom/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) Package version: 0.9.2 not found
(anonymous function) @ sync-settings.coffee:304(anonymous function) @ package-manager.coffee:177exit @ package-manager.coffee:27triggerExitCallback @ /usr/share/atom/resources/app.asar/src/buffered-process.js:215(anonymous function) @ /usr/share/atom/resources/app.asar/src/buffered-process.js:229(anonymous function) @ /usr/share/atom/resources/app.asar/src/buffered-process.js:100emitOne @ events.js:82emit @ events.js:169(anonymous function) @ net.js:469
```

`apm view` shows the version 1.0.3:

```
$ apm view seti-ui
seti-ui
├── 1.0.3
├── https://github.com/jesseweed/seti-ui
├── A dark colored UI theme for Atom with custom file icons.
├── 1392 downloads
└── 1 star

Run `apm install seti-ui` to install this package.
```

I would expect the restore to either
- Install the latest package version
  or
- check if there is a newer version, if the version in the backup can't be installed.

**Comment by dirk-thomas** [comment]
The recent PR #311 should create a notification in case a package installation fails.

Therefore I will close this ticket for now. If this doesn't fix the described problem please comment here and the ticket can be reopened.
