### ISSUE TITLE
Uncaught Error: Cannot find module 'github4'

### ISSUE THREAD

**Issue by craftjk** [atom-community/sync-settings#268]
[Enter steps to reproduce below:]

1. I just installed sync settings. Nothing else.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.10
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: Cannot find module 'github4'

```
At module.js:340

Error: Cannot find module 'github4'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Immediate._onImmediate (/Users/kcraft/.atom/packages/sync-settings/lib/sync-settings.coffee:26:25)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -4:11.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:11.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:11.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:11.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:11.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:11.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:11 core:move-right (atom-text-editor.editor.is-focused)
     -4:10.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:05.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:05.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:04.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:04.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:04.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:02.8.0 core:save (atom-text-editor.editor.is-focused)
     -3:42.1.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -0:31.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by MateuszFlisikowski** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2


### Stack Trace

Uncaught Error: Cannot find module 'github4'

```
At C:\Users\mateusz\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:280

Error: Cannot find module 'github4'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\mateusz\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\mateusz\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Immediate._onImmediate (C:\Users\mateusz\.atom\packages\sync-settings\lib\sync-settings.coffee:26:25)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -4:01.2.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -3:59.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:59 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:07.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:55.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:51.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:50.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
`github4` is a dependency of this package (https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/package.json#L32) and should be installed automatically when `sync-settings` is installed. If you have clone the repository manually you will need to install the dependencies with `npm install`.

**Comment by dirk-thomas** [comment]
`github4` is a dependency of this package (https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/package.json#L32) and should be installed automatically when `sync-settings` is installed. Please try to reinstall the package.

If you have clone the repository manually you will need to install the dependencies with `npm install`.

I will close this ticket for now. Please feel free if the problem happens again and this can be reopened.

**Comment by MateuszFlisikowski** [comment]
ok thx.
