### ISSUE TITLE
Uncaught Error: Cannot find module 'clone'

### ISSUE THREAD

**Issue by Mash19** [atom-community/sync-settings#269]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: Cannot find module 'clone'

```
At module.js:340

Error: Cannot find module 'clone'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Michael\.atom\packages\sync-settings\node_modules\analytics-node\lib\index.js:2:13)
    at Module._compile (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at C:\Users\Michael\.atom\packages\sync-settings\lib\tracker.coffee:13:24
    at exports.allowUnsafeEval (C:\Users\Michael\.atom\packages\sync-settings\node_modules\loophole\lib\loophole.js:14:14)
    at Object.<anonymous> (C:\Users\Michael\.atom\packages\sync-settings\lib\tracker.coffee:12:3)
    at Object.<anonymous> (C:\Users\Michael\.atom\packages\sync-settings\lib\tracker.coffee:108:4)
    at Module._compile (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Michael\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Immediate._onImmediate (file:///C:/Users/Michael/.atom/packages/sync-settings/lib/sync-settings.coffee:26:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Atom-Syntax-highlighting-for-Sass",
      "linter-scss-lint",
      "sass-compiler"
    ],
    "projectHome": "C:\\Users\\mash\\Documents"
  }
}
```

### Installed Packages

```coffee
# User
angularjs-boilerplate-snippets, v0.3.1
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.3
atom-jasmine, v0.8.1
atom-jsx-transform, v0.2.0
build-grunt, v0.4.0
caniuse, v0.9.0
color-picker, vundefined
css-color-underline, v1.0.1
docblockr, v0.7.3
emmet, v2.4.3
grunt-runner, v0.14.0
gulp-snippets, v0.6.2
jslint, v1.5.1
linter, v1.11.4
linter-doiuse, v0.2.3
linter-eslint, v7.1.3
linter-jsxhint, v0.1.2
minimap, v4.21.0
source-preview-babel, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
sync-settings, v0.7.2
takana-atom, vundefined
tree-view-git-status, v0.2.3
w3c-validation, v0.4.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment]
It looks like a recursive dependency was not installed correctly. I would recommend to try reinstalling the package.

**Comment by dirk-thomas** [comment]
I will close this ticket for now since there is nothing to be done in this package. Please feel free to comment here if the problem happens again.
