### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, open '$ATOM_HOME/storage'

### ISSUE THREAD

**Issue by tfoote** [atom-community/sync-settings#282]
[Enter steps to reproduce below:]

1. Install a fresh computer
2. Install a fresh version of atom
3. Install the sync settings plugin
4. Set the gist ID and token appropriately
5. Invoke `sync-settings: Restore`

Removing the directory `~/.atom/storage` resolved the problem. 
```
~/.atom/storage Last: [0] (0s Seconds)
$ ls
application.json
```

After successfully running there is now a file `~/.atom/storage` with the contents
```
~/.atom Last: [0] (0s Seconds)
$ cat storage 
This is a place holder
```

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, open '/home/tfoote/.atom/storage'

```
At fs.js:584

Error: EISDIR: illegal operation on a directory, open '/home/tfoote/.atom/storage'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at /home/tfoote/.atom/packages/sync-settings/lib/sync-settings.coffee:233:19
    at /home/tfoote/.atom/packages/sync-settings/node_modules/github4/index.js:759:17
    at callCallback (/home/tfoote/.atom/packages/sync-settings/node_modules/github4/index.js:613:17)
    at IncomingMessage.<anonymous> (/home/tfoote/.atom/packages/sync-settings/node_modules/github4/index.js:671:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
     -3:49.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:22.8.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
  3x -0:30.6.0 command-palette:toggle (input#sync-settings.syncSettings.)
  2x -0:07.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 sync-settings:restore (input#sync-settings.syncSettings.)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-puppet-lint",
      "pep8",
      "linter-python-pep8"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "REMOVED WHEN FILING TICKET",
    "gistId": "REMOVED WHEN FILING TICKET",
    "personalAccessToken": "REMOVED WHEN FILING TICKET"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
It looks like your gist contains the file `storage` (https://github.com/atom-community/sync-settings/blob/e0f3f2fbe7d0001cb4da94f56835e8ba65188f89/lib/sync-settings.coffee#L233) which collides with the folder being present in the `.atom` folder. If that is the case then you should delete the file from your gist and it should work again.

**Comment by tfoote** [comment]
Yes, it had a storage file. Removing that from the gist manually lets it restore properly.
