### ISSUE TITLE
Uncaught TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by tasi788** [atom-community/sync-settings#291]
[Enter steps to reproduce below:]

1. Open new file and type someting
2. and press alt+command+G run gist up
3. press Gist it and get err msg

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught TypeError: The header content contains invalid characters

```
At _http_outgoing.js:348

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:196:15)
    at Object.request (/Users/TSAI/.atom/packages/sync-settings/node_modules/github4/node_modules/agent-base/patch-core.js:52:20)
    at Gist.module.exports.Gist.post (/Users/TSAI/.atom/packages/gist-it/lib/gist-model.coffee:48:24)
    at GistView.module.exports.GistView.gistIt (/Users/TSAI/.atom/packages/gist-it/lib/gist-view.coffee:134:11)
    at HTMLButtonElement.<anonymous> (/Users/TSAI/.atom/packages/gist-it/lib/gist-view.coffee:52:33)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -8:16.8.0 gist-it:gist-current-file (div.package-detail.panels-item)
     -8:09.1.0 core:paste (atom-text-editor#sync-settings.gistId.editor.mini.is-focused)
     -7:36.2.0 sync-settings:backup (atom-text-editor.editor.is-focused)
     -6:39.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:47.3.0 tree-view:remove (span.name.icon.icon-file-text)
     -5:41.8.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:40.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:37.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:36.4.0 gist-it:gist-current-file (atom-text-editor.editor.is-focused)
     -5:34.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -5:21.3.0 gist-it:gist-current-file (atom-text-editor.editor.is-focused)
     -1:16.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:14.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 gist-it:gist-current-file (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "cht-menu"
    ],
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "xxx",
    "_lastBackupHash": "xx",
    "gistId": "xxxxx",
    "personalAccessToken": "xxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (active)
atom-runner, v2.7.1 (inactive)
auto-update-packages, v1.0.1 (active)
file-icons, v1.7.19 (active)
gist-it, v0.9.1 (active)
git-plus, v5.16.2 (inactive)
highlight-line, v0.11.1 (active)
linter, v1.11.16 (active)
livereload, v0.4.4 (active)
minimap, v4.24.7 (active)
python-indent, v0.4.3 (active)
scroll-sync, v0.1.5 (inactive)
sync-settings, v0.7.2 (active)
tabs-to-spaces, v1.0.2 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment]
Is the error happening repeatedly for you? Is it related to your config? Does it also happen with a clean profile?

**Comment by tasi788** [comment]
@dirk-thomas thanks for remind

**Comment by tasi788** [comment]
Which config ?
`sync-settings` or `atom`

**Comment by dirk-thomas** [comment]
Anything you backup to the Gist. So the `config.cson` from Atom, and every other config you have selected in the `sync-settings` settings.

We need to figure out if it fails due to some content in your Atom configuration.

**Comment by tasi788** [comment]
I'm sorry that I forgot gave more detail this err
i do it like this:
1.Open new file and type something
2.and press alt+command+G run [`gist it`](https://atom.io/packages/gist-it)
3.press Gist it and get err msg

**Comment by dirk-thomas** [comment]
And the automatic error report filled the ticket in this repo? Or did you create the ticket by hand?

Anyway your problem is with using `gist-it` which is a different package. You might want to report the problem there instead: https://github.com/rpowelll/gist-it

**Comment by tasi788** [comment]
yes, it automatic to filled this ticket
I'll report it to `gist-it`later anyway thanks a lot.
