### ISSUE TITLE
Uncaught Error: EIO: i/o error, open '$ATOM_HOME/compile-cache/coffee/c11c6c8d7d38ed05edd64dfd2b4...

### ISSUE THREAD

**Issue by brenohq** [atom-community/sync-settings#292]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: "Manjaro Linux"
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: EIO: i/o error, open '/home/brenohq/.atom/compile-cache/coffee/c11c6c8d7d38ed05edd64dfd2b429a8575725564.js'

```
At fs.js:584

Error: EIO: i/o error, open '/home/brenohq/.atom/compile-cache/coffee/c11c6c8d7d38ed05edd64dfd2b429a8575725564.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at writeCachedJavascript (/usr/share/atom/resources/app.asar/src/compile-cache.js:97:6)
    at compileFileAtPath (/usr/share/atom/resources/app.asar/src/compile-cache.js:78:7)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Immediate._onImmediate (/home/brenohq/.atom/packages/sync-settings/lib/sync-settings.coffee:25:25)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-bootlint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-slate"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "c0eaecda-46ea-4e30-812e-8796208d0084",
    "_lastBackupHash": "0a2de158b41e83fdd7ad91829d501649bde68676",
    "gistId": "87df26c293f820bc0d179b8262296716",
    "personalAccessToken": "xxxxx"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0 (active)
autocomplete-paths, v1.0.2 (active)
exception-reporting, v0.40.0 (active)
git-plus, v5.16.2 (inactive)
javascript-snippets, v1.2.1 (active)
language-blade, v0.25.3 (inactive)
linter, v1.11.16 (active)
linter-gcc, v0.6.15 (active)
linter-jshint, v2.1.0 (active)
linter-php, v1.2.0 (active)
metrics, v1.0.0 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
monokai-slate, v0.5.0 (active)
seti-icons, v1.3.3 (active)
sync-settings, v0.7.2 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment]
While the stacktrace shows `sync-settings` I don't think there is anything this package can do different. So I will close this ticket for now since there is nothing I am aware of we could do here.
