### ISSUE TITLE
Uncaught Error: Cannot find module 'estraverse'

### ISSUE THREAD

**Issue by Vanni-Fan** [atom-community/sync-settings#303]
```
C:\Users\user\AppData\Local\atom\app-1.12.0-beta3\resources\app.asar\src\module-cache.js:364
Hide Stack Trace
Error: Cannot find module 'estraverse'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.12.0-beta3\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.12.0-beta3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\degenerator\node_modules\escodegen\escodegen.js:64:18
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\degenerator\node_modules\escodegen\escodegen.js:2282:2)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\degenerator\index.js:8:17)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\index.js:9:19)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\index.js:35:19)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\index.js:8:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\node_modules\superagent-proxy\index.js:6:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (C:\Users\user\.atom\packages\sync-settings\node_modules\analytics-node\lib\index.js:6:1)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at file:///C:/Users/user/.atom/packages/sync-settings/lib/tracker.coffee:10:32
    at exports.allowUnsafeEval (C:\Users\user\.atom\packages\sync-settings\node_modules\loophole\lib\loophole.js:14:14)
    at Object.<anonymous> (file:///C:/Users/user/.atom/packages/sync-settings/lib/tracker.coffee:10:1)
    at Object.<anonymous> (file:///C:/Users/user/.atom/packages/sync-settings/lib/tracker.coffee:2:1)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Immediate.<anonymous> (file:///C:/Users/user/.atom/packages/sync-settings/lib/sync-settings.coffee:26:18)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

**Comment by Vanni-Fan** [comment]
In Atom 1.12.0-beta3

**Comment by dirk-thomas** [comment]
You might want to uninstall and reinstall the package. Often that help to resolve these kind of issues.

**Comment by Vanni-Fan** [comment]
I follow you step ,Is fixed now. Thanks!
