### ISSUE TITLE
Node_module dependency typo — Uncaught ReferenceError: namespae is not defined

### ISSUE THREAD

**Issue by callumflack** [atom-community/sync-settings#325]
For sync-settings 0.8.0 on OSX 10.12.1, I get a typo in the debug node_module dependency:

/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/debug/debug.js:126
Hide Stack Trace
ReferenceError: namespae is not defined
    at createDebug (/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/debug/debug.js:126:29)
    at Object.<anonymous> (/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/https-proxy-agent/https-proxy-agent.js:12:29)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at global.httpSend (/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/github/lib/index.js:602:31)
    at global.handler (/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/github/lib/index.js:790:14)
    at Object.self.(anonymous function).(anonymous function) [as get] (/Users/sticktoitiveness/.atom/packages/sync-settings/node_modules/github/lib/index.js:271:34)
    at Object.checkForUpdate (/Users/sticktoitiveness/.atom/packages/sync-settings/lib/sync-settings.coffee:71:29)
    at Immediate.<anonymous> (/Users/sticktoitiveness/.atom/packages/sync-settings/lib/sync-settings.coffee:39:8)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by dirk-thomas** [comment]
The problem seems to not come from `sync-settings` but one of its dependencies. Please try to uninstall and reinstall `sync-settings` and check if the problem goes away. If not can you please post the version information of that `debug` package.

**Comment by vatscy** [comment]
This error occurs due to [this bug](https://github.com/visionmedia/debug/issues/347).
because `follow-redirects` and `https-proxy-agent` depend on `debug` and `github` depends on that two packages, maybe it needs to update `github` package.

**Comment by dirk-thomas** [comment]
`follow-redirects` 1.2.1 has updated the mininum version for the `debug` dependency. But for `https-proxy-agent` there is no new release yet. See TooTallNate/node-https-proxy-agent#21 for the proposed PR.

**Comment by dirk-thomas** [comment]
I will close this issue now since quite some time has passed since then and it is unlikely that users will still run into this and need the open ticket for help.
