### ISSUE TITLE
"Uncaught TypeError: PackageManager is not a constructor" at restore

### ISSUE THREAD

**Issue by K4zuki** [atom-community/sync-settings#332]
* This happened when selecting restore-from-backup
* The package seems trying to install first package in list(blue popup also appears)

---

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.8.1

### Stack Trace

Uncaught TypeError: PackageManager is not a constructor

```
At /C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:516

TypeError: PackageManager is not a constructor
    at Object.installPackage (file:///C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:357:26)
    at file:///C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:329:12
    at file:///C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:328:9
    at Object.installMissingPackages (file:///C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:352:7)
    at file:///C:/Users/tklab/.atom/packages/sync-settings/lib/sync-settings.coffee:234:16
    at C:\Users\tklab\.atom\packages\sync-settings\node_modules\github\lib\index.js:819:17
    at callCallback (C:\Users\tklab\.atom\packages\sync-settings\node_modules\github\lib\index.js:667:17)
    at IncomingMessage.<anonymous> (C:\Users\tklab\.atom\packages\sync-settings\node_modules\github\lib\index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:12.1.0 sync-settings:restore (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "build-tools",
      "markdown-preview",
      "build-tools-make",
      "terminal-plus",
      "markdown-preview-plus"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false,
    "fontFamily": "Ricty Diminished",
    "packagesWithKeymapsDisabled": [
      "rst-preview-pandoc",
      "build"
    ],
    "projectHome": "W:\\Tokyo\\Home\\kyamamot\\common\\GitHub"
  },
  "sync-settings": {
    "_analyticsUserId": "1c36811b-1866-4678-8825-d4a7b5b7d659",
    "_lastBackupHash": "2bd076bc99716fc87cb7234edb77568751263a34",
    "checkForUpdatedBackup": false,
    "gistId": "66d86bbf142a60499cd7",
    "personalAccessToken": "xxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-gooey-syntax, v0.2.1 (inactive)
build, v0.67.0 (active)
build-make, v0.13.0 (active)
busy, v0.7.0 (active)
env-from-shell, v0.3.0 (inactive)
file-icons, v1.7.25 (active)
genesis-ui, v0.5.0 (inactive)
git-control, v0.8.2 (inactive)
git-plus, v7.0.5 (active)
git-projects, v1.17.0 (inactive)
gl-light-syntax, v2.2.0 (inactive)
highlight-line, v0.11.2 (active)
idiomatic-dark-syntax, v0.1.3 (inactive)
iso8601-timestamp, v0.1.1 (inactive)
japanese-word-selection, v0.4.0 (active)
language-doxygen, v0.2.1 (active)
language-ini, v1.17.0 (active)
latex, v0.39.1 (inactive)
mac-fix-path, v0.0.0 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-enhanced, v0.8.9 (active)
markdown-preview-plus, v2.4.0 (inactive)
markdown-table-formatter, v2.8.4 (active)
minimap, v4.25.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
native-ui, v0.19.1 (inactive)
octocat-syntax, v0.1.5 (inactive)
open-recent, v5.0.0 (active)
pdf-view, v0.54.0 (active)
platformio-ide-terminal, v2.2.2 (active)
python-autopep8, v0.1.3 (active)
release-notes, v0.53.0 (active)
rst-preview-pandoc, v0.1.12 (active)
script, v3.13.0 (inactive)
slack-ui, v0.7.0 (inactive)
svn, v0.0.13 (active)
sync-settings, v0.8.1 (active)
tablr, v1.5.5 (active)
tango-syntax, v0.4.1 (inactive)
terminal-plus, v0.14.5 (inactive)
tool-bar, v1.0.1 (active)
tool-bar-atom, v1.7.0 (active)
tool-bar-main, v0.0.10 (active)
tool-bar-markdown-writer, v0.2.0 (active)
tortoise-svn, v0.5.0 (inactive)
tree-view-git-status, v1.3.0 (active)
vs-dark-syntax, v1.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment]
Did you invoke the command directly after starting Atom? The package might not have been activated completely yet.

Can you reproduce the problem (after waiting a bit after starting Atom)?

**Comment by K4zuki** [comment]
@dirk-thomas thanks to pointing about access token; it is hidden now

- the problem reproduces on one machine. the error happens on the same machine even after 10-days' wait.
- also happened after machine reboot, start atom, few minutes to wait.
- from menu -> "check for updated backup" shows correct(orange-brown) popup 
    which tells me it is updated. the popup has restore button, click it, same error shows up.

Should I reinstall atom to test more maybe? the machine in trouble is not used that much frequently

**Comment by dirk-thomas** [comment]
I would recommend to first try to uninstall sync-settings, restart Atom, reinstall sync-settings, restart Atom again. Reinstalling all of Atom should be only a last resort (and it is not clear that this would fix it either).

If you are familiar with setting up this package in development mode and adding some debug output you could check if [this line](https://github.com/atom-community/sync-settings/blob/a8fe7a74af343d7e58ff459c9b2e981eeb6f9369/lib/sync-settings.coffee#L25) is happening correctly.

**Comment by K4zuki** [comment]
still it is not good:

- uninstall package -> restart atom -> install package -> restart atom -> restore ->NG

I tried debug mode but I am not sure _the line_ is properly working or not
I am not JS experienced but I suppose _the line_ imports/includes source 
from local; I _think_ this part is working - error message says line 516 of 
`sync-settings.coffee` while this file does not have 500+ lines of code.

I will try debug mode again anyway(after searching around about atom's debug mode)

**Comment by dirk-thomas** [comment]
I would suggest adding a line to print some debug message around the previously referenced line: `console.log('this is happening')`.

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
