### ISSUE TITLE
Atom Fails To Load Properly - No Packages, Interface Fails

### ISSUE THREAD

**Issue by lacostenycoder** [atom-community/sync-settings#335]
A few days ago, something unknown caused my install of Atom to fail.  When I started the app, the interface froze, no editor windows would open, no settings available.  I fully uninstalled Atom using AppCleaner to remove any hidden associated files etc.  I did clean install, worked fine.  When I re-synced from gist backup, I got the same behavior.  I'm guessing it was some package but there was no way for me to know.  My only recourse was to do another uninstall / reinstall but this time not use sync-settings and only add packages I frequently use manually.  Also had to set all my configs manually, custom keys, colors, prefs etc.  Luckily I was able to use info from the sync-settings gist to decide what to do, but a lot of time spent getting things back to how I'm used to working. 

Any ideas how to fix/improve this or figure out what went wrong for me?

**Comment by dirk-thomas** [comment]
You could manually restore the state of an older revision from the gist. If that works out would be interesting what the difference to a newer revision is which didn't work anymore.

Maybe by looking at the revision history you might already get an idea what could be causing it.

**Comment by lacostenycoder** [comment]
@dirk-thomas It seems that the gist only contains 2 revisions, the init which had no files, and a single backup dated May 21, 2016 with `6 changed files with 843 additions and 0 deletions.`.
Most of which are in the packages.json file.  I looked through everything and nothing jumps out as appear broken except perhaps:

```
{
+		"name": "incompatible-packages",
+		"version": "0.25.1"
+	},
```

I suppose I could have tried editing this file, adding packages one by one, but I didn't see the point.  I opted for clean install and only adding a handful of packages I need / use regularly.
I was able to restore my custom styles from `styles.less`.  It feels good to have a clean trimmed down install.  But still weird that I can't figure out exactly what went wrong, when, or why.

**Comment by dirk-thomas** [comment]
That entry is just a "normal" Atom package, see https://atom.io/packages/incompatible-packages

I guess without more information there is not much we can do here.

**Comment by agawley** [comment]
I have this same bug. My gist is here: https://gist.github.com/agawley/43b5b0577526a39fa0976cf61eeeeb23

**Comment by agawley** [comment]
My errors on restore:

```
/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:35
Hide Stack Trace
CssSyntaxError: <css input>:3:29: Unclosed quote
  1 | atom-text-editor {
  2 |   font-size: 14px;
> 3 |   font-family: Operator Mono', "Apple Color Emoji";
    |                             ^
  4 |   line-height: 1.5;
  5 | }
    at Input.error (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/input.js:113:22)
    at unclosed (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:57:21)
    at tokenize (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:167:29)
    at Parser.tokenize (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parser.js:49:46)
    at Function.parse (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:25:16)
    at transformDeprecatedShadowDOMSelectors (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/style-manager.js:253:37)
    at StyleManager.addStyleSheet (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/style-manager.js:148:23)
    at atom-workspace.module.exports.WorkspaceElement.updateGlobalTextEditorStyleSheet (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:73:19)
    at /private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/private/var/folders/s8/3glwh35d0tg602slw43dvv34000nz0/T/AppTranslocation/A5A51D19-89D5-4471-BB19-1593CCACCF64/d/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Object.applySettings (/Users/alexg/.atom/packages/sync-settings/lib/sync-settings.coffee:301:21)
    at Object.applySettings (/Users/alexg/.atom/packages/sync-settings/lib/sync-settings.coffee:298:10)
    at /Users/alexg/.atom/packages/sync-settings/lib/sync-settings.coffee:229:14
    at /Users/alexg/.atom/packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/Users/alexg/.atom/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at IncomingMessage.<anonymous> (/Users/alexg/.atom/packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by agawley** [comment]
Well looks like i just messed up the CSS. When I fix that Operator Mono thing, everything is hunky dory.
