### ISSUE TITLE
Uncaught Error: Cannot find module 'github'

### ISSUE THREAD

**Issue by tungv** [atom-community/sync-settings#345]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.1

### Stack Trace

Uncaught Error: Cannot find module 'github'

```
At module.js:457

Error: Cannot find module 'github'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/tung/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/sync-settings/lib/sync-settings.coffee:24:20)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -3:22.3.0 core:close (atom-pane.pane.active)
     -3:17.1.0 settings-view:open (input.hidden-input)
  3x -0:56.5.0 core:backspace (input.hidden-input)
     -0:51.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
sync-settings 0.8.1 
```

**Comment by dirk-thomas** [comment]
Please try to in and reinstall the package (and restart Atom).

**Comment by dirk-thomas** [comment]
I assume the problem has been solve with the previous comment.
