### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, open '$ATOM_HOME/dicts'

### ISSUE THREAD

**Issue by fhchl** [atom-community/sync-settings#356]
This was thrown just know when I wanted to restore my settings. I am using Atom on a Mac and PC and syncing the settings between them with this nice package.

dicts is a folder in my ".atom" that I also like to keep synced between the two machines by setting the

```
extraFiles: [
      "dicts"
    ]
```

options in my config.

[Enter steps to reproduce:]

1. Executing command "Sync Settings: Restore"

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.1

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, open 'C:\Users\fmheu\.atom\dicts'

```
At fs.js:640

Error: EISDIR: illegal operation on a directory, open 'C:\Users\fmheu\.atom\dicts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at /packages/sync-settings/lib/sync-settings.coffee:248:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:50.5.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:14.8.0 project-manager:list-projects (input.hidden-input)
     -0:13.4.0 editor:consolidate-selections (input.hidden-input)
     -0:13.4.0 core:cancel (input.hidden-input)
     -0:12.8.0 intentions:highlight (input.hidden-input)
     -0:12.6.0 command-palette:toggle (input.hidden-input)
  9x -0:09.2.0 core:backspace (input.hidden-input)
     -0:04.6.0 core:confirm (input.hidden-input)
     -0:04.6.0 application:open-your-config (input.hidden-input)
     -0:00.3.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-latex 0.7.4 
autocomplete-bibtex 0.7.0 
autocomplete-python 1.8.62 
autoupdate-packages 1.3.1 
busy-signal 1.3.0 
editorconfig 2.2.2 
file-icons 2.1.2 
git-plus 7.3.3 
highlight-selected 0.13.1 
imdone-atom 2.1.25 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-markdown 0.20.0 
language-pfm 0.82.0 
languagetool 0.1.1 
latex-autocomplete 1.0.0 
linter 2.1.2 
linter-coffeelint 1.2.1 
linter-flake8 2.1.5 
linter-proselint 3.2.1 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.9 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
open-terminal-here 2.3.0 
pdf-view 0.57.0 
project-manager 3.3.4 
script 3.14.1 
split-diff 1.3.0 
sync-settings 0.8.1 
tasks 2.6.6 
wordcount 2.10.4 
```

**Comment by dirk-thomas** [comment]
Does your gist contain an entry `dicts`? What does it contain?

**Comment by fhchl** [comment]
Yes, and it's content is

    # dicts (not found) 

I guess sync settings doesn't support having folders in the "extraFiles"?

**Comment by fhchl** [comment]
If I insert the relative paths to the files into "extraFiles", then backup and restore works as expected. Will this also handle the slash-backslash difference between Mac and Windows?

**Comment by dirk-thomas** [comment]
Yes, `extraFiles` only supports files.

I would assume it works fine for slashes as well as backslashes. Please comment if that is not the case for you.

**Comment by dirk-thomas** [comment]
I assume it worked for you. Since folders are not supported I will close this for now.
