### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dismiss' of undefined

### ISSUE THREAD

**Issue by yuhonyon** [atom-community/sync-settings#361]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dismiss' of undefined

```
At /Users/ks/.atom/packages/sync-settings/lib/sync-settings.coffee:331

TypeError: Cannot read property 'dismiss' of undefined
    at /packages/sync-settings/lib/sync-settings.coffee:331:36
    at /packages/sync-settings/lib/sync-settings.coffee:363:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -7:48.5.0 core:confirm (input.hidden-input)
  2x -2:30.7.0 core:paste (input.hidden-input)
     -1:54.7.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
  3x -1:52.6.0 core:backspace (input.hidden-input)
     -1:42.6.0 sync-settings:restore (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-live-server 2.1.2 
atom-miku 2.2.5 
atom-minify 0.8.0 
atom-monokai 0.10.9 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
bracket-close-jump 0.1.2 
busy-signal 1.4.1 
context-menu-manager 0.2.0 
css-snippets 1.1.0 
docblockr 0.9.4 
emmet 2.4.3 
file-icons 2.1.4 
git-plus 7.8.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
language-babel 2.58.0 
language-vue 0.21.2 
linter 2.1.4 
linter-jshint 3.0.3 
sync-settings 0.8.1 
```

**Comment by dirk-thomas** [comment]
Please describe what you did when the error occurred / steps to reproduce the problem.

**Comment by dirk-thomas** [comment]
Closing due to no response. Please feel free to comment with the additional information and the ticket can be reopened.

**Comment by vpn** [comment]
@dirk-thomas I have now gotten this issue.

I was setting up Atom on a new machine. This was the first package I installed. I entered my gistID and Access Token, then ran the command sync-settings: restore.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro (Version 1709 (Build 16299.125))
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3


### Stack Trace

Uncaught TypeError: Cannot read property 'dismiss' of undefined

```
At C:\Users\patri\.atom\packages\sync-settings\lib\sync-settings.coffee:396

TypeError: Cannot read property 'dismiss' of undefined
    at /packages/sync-settings/lib/sync-settings.coffee:396:36
    at /packages/sync-settings/lib/sync-settings.coffee:428:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (~/AppData/Local/atom/app-1.23.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.23.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -8:38.7.0 core:confirm (input.hidden-input)
  2x -7:53 core:paste (input.hidden-input)
     -7:12.7.0 grammar-selector:show (div.panels-item)
     -7:10.6.0 command-palette:toggle (div.panels-item)
  2x -7:07.3.0 core:move-down (input.hidden-input)
     -7:06.1.0 core:confirm (input.hidden-input)
     -7:06.1.0 sync-settings:restore (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-gooey-syntax 1.0.0 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-python 1.10.3 
block-comment 0.4.3 
busy-signal 1.4.3 
compare-files 0.8.1 
emmet 2.4.3 
file-icons 2.1.12 
grammar-token-limit 0.1.1 
highlight-selected 0.13.1 
intentions 1.1.5 
jshint 1.8.6 
kite 0.45.1 
language-nginx 0.8.0 
linter 2.2.0 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.10 
minimap 4.29.7 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
php-debug 0.2.5 
pigments 0.40.2 
seti-syntax 0.1.7 
seti-ui 1.9.0 
split-diff 1.5.1 
sync-settings 0.8.3 
```
