### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by zhiqianli** [atom-community/sync-settings#368]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/li/AppData/Local/atom/app-1.18.0/resources/app/static/index.html:453

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/sync-settings/lib/sync-settings.coffee:236:44
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:33.5.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
emmet 2.4.3 
sync-settings 0.8.2 
```

**Comment by dirk-thomas** [comment]
Please edit the ticket and insert the steps you did when the problem appeared.

**Comment by dirk-thomas** [comment]
Closing due to no response.

Please feel free to provide more information and the ticket can be reopened.

**Comment by Arcadia822** [comment]
[Enter steps to reproduce:]

1. personal access token: 49b03a620394ad9e86ee4d9b7ac493971659fc69
2. gist id: e41bb60627f24983ea4324fa4e79fe52

sync created with unknown previous version of Atom and sync-settings

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3


### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/sync-settings/lib/sync-settings.coffee:231:37
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:23.2.0 core:move-to-bottom (input.hidden-input)
     -2:20.6.0 core:move-to-top (input.hidden-input)
  6x -2:18.7.0 core:move-down (input.hidden-input)
     -2:15.6.0 command-palette:toggle (input.hidden-input)
     -2:03.0 editor:consolidate-selections (input.hidden-input)
     -2:03.0 core:cancel (input.hidden-input)
     -0:29 command-palette:toggle (input.hidden-input)
  3x -0:26.4.0 core:move-down (input.hidden-input)
     -0:25.7.0 core:move-up (input.hidden-input)
     -0:25.4.0 core:confirm (input.hidden-input)
     -0:25.4.0 sync-settings:restore (input.hidden-input)
     -0:21.5.0 key-binding-resolver:toggle (input.hidden-input)
     -0:19 command-palette:toggle (input.hidden-input)
  3x -0:17.3.0 core:move-down (input.hidden-input)
     -0:16.3.0 editor:consolidate-selections (input.hidden-input)
     -0:16.3.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
advanced-open-file 0.16.7 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-python 1.1.0 
antialiased 0.1.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-json-color 0.6.0 
atom-monokai 0.10.9 
atom-solarized-dark-ui 0.28.1 
atomic-chrome 0.3.2 
aurora-theme 1.2.2 
autocomplete-clang 0.11.3 
autocomplete-modules 1.7.2 
autocomplete-paths 2.12.0 
autocomplete-python 1.10.3 
block-comment-plus 0.5.1 
bottom-dock 0.4.4 
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
colorful-json 1.1.0 
dockerletion 0.2.0 
expose 0.15.0 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
git-control 0.9.0 
git-log 0.4.1 
git-time-machine 1.5.9 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-markdown 0.2.2 
intentions 1.1.5 
language-diff 0.7.0 
language-docker 1.1.8 
language-ini 1.19.0 
line-count 0.5.0 
lines 0.13.1 
linter 2.2.0 
linter-docker 0.2.1 
linter-gcc 0.7.1 
linter-js-standard 4.0.2 
linter-manager 0.2.12 
linter-pep8 1.3.2 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.0 
linter-ui-default 1.6.10 
logo-file-icons 1.12.0 
markdown-mindmap 0.4.2 
markdown-preview-enhanced 0.14.11 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.7.2 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
multiline-tab 0.2.1 
nord-atom-ui 0.11.0 
package-list 0.1.2 
path-hyperclick 0.3.0 
pigments 0.40.2 
platformio-ide 2.0.0-rc.3 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
pretty-json 1.6.4 
python-isort 0.0.7 
rainbow-tabs 2.5.1 
Remote-FTP 1.2.5 
selection-counter 1.0.0 
SFTP-deployment 1.0.2 
solarized-dark-ui 0.3.2 
steam-pirate-syntax 0.3.0 
steam-pirate-ui 0.6.1 
sync-settings 0.8.3 
tab-close 2.1.0 
tasks 2.6.7 
todo-manager 0.2.10 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
tree-view-git-status 1.4.0 
wakatime 7.0.3 
webbox-color 0.5.9 
```
