### ISSUE TITLE
Uncaught Error: Cannot find module './package-manager'

### ISSUE THREAD

**Issue by wangminghuan** [atom-community/sync-settings#370]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.2

### Stack Trace

Uncaught Error: Cannot find module './package-manager'

```
At C:\Users\ThinkPad\AppData\Local\atom\app-1.18.0\resources\app\static\<embedded>:1

Error: Cannot find module './package-manager'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/lib/sync-settings.coffee:25:25)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
sync-settings 0.8.2 
```

**Comment by dirk-thomas** [comment]
The `package-manager.coffee` file is a sibling of the file `sync-settings.coffee` listed in the stacktrace. Can you please check if the file actually exists in the filesystem? I would recommend to reinstall the package - maybe something when wrong during `apm install`.

**Comment by dirk-thomas** [comment]
Closing due to no response.

Please feel free to provide more information and the ticket can be reopened.
