### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/init.coffee'

### ISSUE THREAD

**Issue by hugeme** [atom-community/sync-settings#373]
[Enter steps to reproduce:]

Just updated ATOM to 1.18

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/user/.atom/init.coffee'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/user/.atom/init.coffee'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at /packages/sync-settings/lib/sync-settings.coffee:247:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:05.8.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
ask-stack 2.2.0 
atom-beautify 0.30.3 
atom-python-run 0.7.3 
auto-encoding 0.7.0 
auto-update-packages 1.0.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
browser-plus 0.0.98 
build 0.68.0 
build-rscript 0.6.2 
busy 0.7.0 
busy-signal 1.4.3 
data-atom 0.25.2 
Ensime 0.41.0 
gist 1.0.0 
git-projects 1.17.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
Hydrogen 1.19.0 
hyperclick 0.1.2 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-latex 1.0.0 
language-markdown 0.23.0 
language-mongodb 0.3.1 
language-pgsql 0.2.3 
language-r 0.4.1 
language-scala 1.1.8 
language-sql-mysql 0.3.1 
latex 0.44.0 
latex-autocomplete 1.0.0 
latextools 0.8.5 
linter 2.2.0 
linter-ui-default 1.6.2 
MagicPython 1.0.10 
markdown-writer 2.6.5 
minimap-highlight-selected 4.6.1 
open-html-in-browser 0.1.0 
open-recent 5.0.0 
pdf-view 0.59.0 
platformio-ide-terminal 2.5.3 
project-manager 3.3.5 
python-debugger 0.2.0 
python-indent 1.1.0 
python-tools 0.6.9 
qolor 0.4.2 
quick-query 0.10.2 
r-exec 0.5.0 
sbt 0.12.0 
scala-format 0.1.8 
sync-settings 0.8.2 
tasks 2.6.6 
todo-show 1.11.0 
```

````
~/.atom  $ ls
blob-store              github.cson             kite-config.json        snippets.cson
compile-cache           init.coffee             packages                split-diff
config.cson             initialInstall.txt      projects.cson           storage
git-time-machine        keymap.cson             recovery                styles.less
```
File init.coffee is present but empty. Not sure what to do.

**Comment by njZhuMin** [comment]
I remove `init.coffee` and `snippets.cson`, and run restore again. The trick just works. Don't know why.
(Archlinux restore from Mac backup)
