### ISSUE TITLE
Uncaught Error: EIO: i/o error, read

### ISSUE THREAD

**Issue by haleksandre** [atom-community/sync-settings#390]
[Enter steps to reproduce:]

1. Happens on Atom launch

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3

### Stack Trace

Uncaught Error: EIO: i/o error, read

```
At fs.js:656

Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Proxy.fs.readFileSync (fs.js:486:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at compileFileAtPath (/usr/share/atom/resources/app/src/compile-cache.js:89:29)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/node_modules/https-proxy-agent/https-proxy-agent.js:12:13)
    at /packages/sync-settings/node_modules/https-proxy-agent/https-proxy-agent.js:204:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at module.exports.httpSend (/packages/sync-settings/node_modules/github/lib/index.js:602:31)
    at module.exports.handler (/packages/sync-settings/node_modules/github/lib/index.js:790:14)
    at /packages/sync-settings/node_modules/github/lib/index.js:271:34)
    at Object.checkForUpdate (/packages/sync-settings/lib/sync-settings.coffee:71:29)
    at /packages/sync-settings/lib/sync-settings.coffee:39:8)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:22.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
atom-beautify 0.30.6 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-ternjs 0.18.3 
blade-snippets 0.2.0 
browser-refresh 0.9.0 
busy-signal 1.4.3 
compare-files 0.8.1 
dash-syntax 0.4.1 
dash-ui 0.4.4 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
editorconfig 2.2.2 
file-icons 2.1.13 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-api-blueprint 1.0.2 
language-babel 2.77.0 
language-blade 0.36.0 
language-docker 1.1.8 
language-graphql 0.9.0 
language-htaccess 0.1.1 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-pug 0.0.21 
language-twig 1.6.3 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-js-yaml 1.2.8 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-pug 1.3.1 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
node-debugger 1.10.1 
php-debug 0.2.5 
pigments 0.40.2 
prettier-atom 0.40.0 
project-manager 3.3.5 
sort-lines 0.18.0 
sprinkles-syntax 2.1.0 
symbol-gen 1.3.1 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
travis-ci-status 1.3.1 
```

**Comment by UziTech** [comment]
if this is still an issue in the latest version feel free to reopen
