### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by Luokem** [atom-community/sync-settings#409]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.4

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of undefined

```
At C:\Users\11071\.atom\packages\sync-settings\lib\sync-settings.coffee:265

TypeError: Cannot read property 'substr' of undefined
    at Object.createClient (/packages/sync-settings/lib/sync-settings.coffee:265:66)
    at Object.restore (/packages/sync-settings/lib/sync-settings.coffee:213:6)
    at /packages/sync-settings/lib/sync-settings.coffee:30:10)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:287:16)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:222:37)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:449:16)
```

### Commands

```
  3x -8:24.1.0 core:backspace (input.hidden-input)
     -1:53.5.0 core:paste (div.line)
     -0:44.4.0 command-palette:toggle (input.hidden-input)
  7x -0:41.6.0 core:backspace (input.hidden-input)
     -0:28.9.0 sync-settings:restore (input.hidden-input)
```

### Non-Core Packages

```
sync-settings 0.8.4 
```

**Comment by dirk-thomas** [comment]
@Luokem Please provide steps to reproduce the problem.

@kusma FYI. This looks like a regression of your patch #395.

**Comment by kusma** [comment]
@dirk-thomas: Hmmpf, yeah. Seems like this makes what would usually be bad output turn into a crash :(

**Comment by dirk-thomas** [comment]
@kusma Can you please look into possible fixes and create a PR for this. Thank you.

**Comment by kusma** [comment]
@dirk-thomas: Sure, sorry for messing this up in the first place.

But after playing around a bit, it's unclear to me how this can trigger in the first place. If I try not to fill in the "Personal Access Token"-field of the settings, I get an error loading saying:

> sync-settings: Mandatory settings missing: GitHub personal access token

... and the rest of the extension seems to bail out on loading.

Any way, the defensive way to deal with this would probably be:

```patch
diff --git a/lib/sync-settings.coffee b/lib/sync-settings.coffee
index 289b0e9..9ca81d7 100644
--- a/lib/sync-settings.coffee
+++ b/lib/sync-settings.coffee
@@ -262,7 +262,12 @@ SyncSettings =
 
   createClient: ->
     token = @getPersonalAccessToken()
-    console.debug "Creating GitHubApi client with token = #{token.substr(0, 4)}...#{token.substr(-4, 4)}"
+
+    if token
+      console.debug "Creating GitHubApi client with token = #{token.substr(0, 4)}...#{token.substr(-4, 4)}"
+    else
+      console.debug "Creating GitHubApi client without token"
+
     github = new GitHubApi
       version: '3.0.0'
       # debug: true
```

This matches the fact that getPersonalAccessToken() internally seems to think it can get an undefined value. It's unclear to me how, but I seem to be missing something...

Should I send a PR with the above? I'm a bit uneasy trying to fix a problem I can't reproduce...

**Comment by kusma** [comment]
Ah, I can trigger this by having a valid token on start-up, removing it from settings, and then manually trigger restore.

**Comment by kusma** [comment]
OK, if I fix that with the above reproduction, my regression goes away. However, the code still crashes a bit later on, with:
```
Uncaught Error: OAuth2 authentication requires a token or key & secret to be set
    at module.exports.authenticate (C:\Users\erik\.atom\packages\sync-settings\node_modules\github\lib\index.js:334:23)
    at Object.createClient (file:///C:/Users/erik/github/sync-settings/lib/sync-settings.coffee:275:12)
    at Object.restore (file:///C:/Users/erik/github/sync-settings/lib/sync-settings.coffee:213:6)
    at HTMLElement.<anonymous> (file:///C:/Users/erik/github/sync-settings/lib/sync-settings.coffee:30:10)
    at CommandRegistry.handleCommandEvent (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\src\command-registry.js:388:30)
    at Object.didConfirmSelection (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:165:29)
    at SelectListView.confirmSelection (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\command-palette\node_modules\atom-select-list\src\select-list-view.js:388:20)
    at HTMLDivElement.core:confirm (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\command-palette\node_modules\atom-select-list\src\select-list-view.js:93:14)
    at CommandRegistry.handleCommandEvent (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\src\command-registry.js:388:30)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\erik\AppData\Local\atom\app-1.24.0\resources\app.asar\src\window-event-handler.js:108:34)
