### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/*.*'

### ISSUE THREAD

**Issue by bennyatc** [atom-community/sync-settings#415]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Segreteria\.atom\*.*'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\Segreteria\.atom\*.*'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at /packages/sync-settings/lib/sync-settings.coffee:255:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:24.9.0 sync-settings:restore (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
atom-html-preview 0.2.5 
atom-html-templates 0.1.3 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.2.5 
double-tag 1.1.0 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
pigments 0.40.2 
sync-settings 0.8.5 
todo-show 2.2.0 
```

**Comment by dirk-thomas** [comment]
Please share the content of your Gist as well as the settings you are using. `*.*` seems like invalid input to me.

**Comment by dirk-thomas** [comment]
Closing due to no reply.

Please feel free to comment with the requested information and the issue can be reopened if necessary.
