### ISSUE TITLE
Uncaught SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by roycetech** [atom-community/sync-settings#416]
[Enter steps to reproduce:]

1. Restart mac due to update.
2. A dialogue appeared sayng atom is preventing the restart.
3. Go to atom and there is a dialog saying it is out of sync, click the button that you want to refresh your settings.
4. The Error dialogue appears.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught SyntaxError: Unexpected token o in JSON at position 1

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /packages/sync-settings/lib/sync-settings.coffee:236:44
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:18 application:quit (input.hidden-input)
     -0:14 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
sync-settings 0.8.5 
```

**Comment by dirk-thomas** [comment]
Fixed by #422.
