### ISSUE TITLE
Uncaught Error: Cannot find module 'emissary'

### ISSUE THREAD

**Issue by hoonio** [atom-community/sync-settings#418]
[Enter steps to reproduce:]

1. Fresh install atom
2. Settings -> Click install on the left sidebar -> Search for sync-settings -> Click install

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught Error: Cannot find module 'emissary'

```
At module.js:472

Error: Cannot find module 'emissary'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/lib/package-manager.coffee:8:13)
    at /packages/sync-settings/lib/package-manager.coffee:346:4)
    at /packages/sync-settings/lib/package-manager.coffee:350:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/lib/sync-settings.coffee:29:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -1:15.3.0 settings-view:open (atom-pane.pane.active)
  2x -1:04.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
sync-settings 0.8.5 
```

**Comment by UziTech** [comment]
should be fixed in latest version
