### ISSUE TITLE
Uncaught Error: Tried to unload active package 'hyperclick'

### ISSUE THREAD

**Issue by hugeme** [atom-community/sync-settings#420]
Just used `sync - restore`

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught Error: Tried to unload active package 'hyperclick'

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630

Error: Tried to unload active package 'hyperclick'
    at PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:428:20)
    at /packages/sync-settings/lib/sync-settings.coffee:399:12
    at /packages/sync-settings/lib/sync-settings.coffee:398:9
    at /packages/sync-settings/lib/sync-settings.coffee:409:13
    at /packages/sync-settings/lib/sync-settings.coffee:433:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
  4x -9:10.2.0 core:close (atom-pane.pane.active)
     -9:00.4.0 window:toggle-full-screen (atom-pane.pane.active)
     -8:54.1.0 command-palette:toggle (atom-pane.pane.active)
  3x -8:50.2.0 core:backspace (input.hidden-input)
     -8:48.4.0 editor:consolidate-selections (input.hidden-input)
     -8:48.4.0 core:cancel (input.hidden-input)
     -8:47.8.0 settings-view:open (atom-pane.pane.active)
  2x -8:01.2.0 core:paste (input.hidden-input)
     -7:53.9.0 core:close (div.package-detail.panels-item)
     -7:52.7.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -7:50.5.0 core:move-down (input.hidden-input)
     -7:49.4.0 core:confirm (input.hidden-input)
     -7:49.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-python-run 0.9.6 
auto-encoding 0.7.0 
auto-update-packages 1.0.1 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
build 0.70.0 
build-rscript 0.6.2 
busy 0.7.0 
busy-signal 1.4.3 
data-atom 0.26.2 
Ensime 0.41.0 
gist 1.1.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
Hydrogen 2.2.2 
hydrogen-launcher 1.2.1 
hyperclick 0.1.5 
language-scala 1.1.9 
MagicPython 1.0.12 
sync-settings 0.8.5 
```

**Comment by UziTech** [comment]
should be fixed in latest version
