### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by EricDeXin** [atom-community/sync-settings#425]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\zoudexin\AppData\Local\atom\app-1.25.0\resources\app\src\native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/node_modules/github/lib/index.js:8:15)
    at /packages/sync-settings/node_modules/github/lib/index.js:824:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/sync-settings/lib/sync-settings.coffee:24:20)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
autoprefixer 3.7.1 
color-picker 2.2.5 
csscomb 0.3.1 
csslint 1.2.0 
emmet 2.4.3 
file-icons 2.1.18 
javascript-snippets 1.2.1 
sync-settings 0.8.5 
```

**Comment by dirk-thomas** [comment]
Please provide steps to reproduce.

**Comment by grig0ry** [comment]
@dirk-thomas The usual launch of the program is all the steps. #423

**Comment by dirk-thomas** [comment]
The stacktrace doesn't show anything specific beside loading other modules. I would suggest to uninstall and reinstall the package. Other than that I can't help since I can't reproduce the problem.

**Comment by UziTech** [comment]
if this is still an issue feel free to reopen
