### ISSUE TITLE
Cannot read property 'isEqual' of undefined

### ISSUE THREAD

**Issue by usrbowe** [atom-community/sync-settings#427]
[Enter steps to reproduce:]

1. Open Atom
2. It will try to restore settings, but it fails because of error (although some settings are synced)

**Atom**: 1.26.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught TypeError: Cannot read property 'isEqual' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:261

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:715:18)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:324:21)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:321:10)
    at /packages/sync-settings/lib/sync-settings.coffee:241:14
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -0:10.2.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
busy-signal 1.4.3 
ember-tabs 2.4.3 
file-icons 2.1.18 
flow-ide 1.11.0 
git-blame 1.6.0 
git-time-machine 1.5.9 
gruvbox-plus-syntax 1.3.1 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
pigments 0.40.2 
prettier-atom 0.53.0 
sync-settings 0.8.6 
todo-show 2.3.0 
```

**Comment by dirk-thomas** [comment]
The line before the problem happens contains a debug message (see https://github.com/atom-community/sync-settings/blob/49bd959ce51b7d3f9f5738313c76e785f34a021d/lib/sync-settings.coffee#L323-L324). Can you please check the output of the console window and post content here to see what the `key` and `value` is in the case where it fails.

**Comment by usrbowe** [comment]
Ok, here is the console after clicking on Restore:
```js

sync-settings.coffee? [sm]:324 Uncaught TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:715:18)
    at Object.applySettings (/Users/__username__/.atom/packages/sync-settings/lib/sync-settings.coffee:324:21)
    at Object.applySettings (/Users/__username__/.atom/packages/sync-settings/lib/sync-settings.coffee:321:10)
    at /Users/__username__/.atom/packages/sync-settings/lib/sync-settings.coffee:241:14
    at /Users/__username__/.atom/packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/Users/__username__/.atom/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at IncomingMessage.<anonymous> (/Users/__username__/.atom/packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by usrbowe** [comment]
Hi, unfortunately/luckily, I'm no longer able to reproduce the bug. 
My Atom upgraded to `1.26.0-beta1`
Plugin version still same.
