### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEqual' of undefined

### ISSUE THREAD

**Issue by Alex-Linhares** [atom-community/sync-settings#429]
[Enter steps to reproduce:]

1. Had sync all setup and working...
2. Changed themes but didn't sync
3. Atom packages were updated and atom was re-started
4. Sync cannot restore all settings now.  

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught TypeError: Cannot read property 'isEqual' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/src/config.js:1239:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:1175:62)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:1008:23)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:711:18)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:324:21)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:321:10)
    at /packages/sync-settings/lib/sync-settings.coffee:241:14
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  2x -1:08.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-city-lights-syntax.theme-city-lights-ui.teletype-Authenticated)
```

### Non-Core Packages

```
ask-stack 2.2.0 
autocomplete-bibtex 1.2.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
file-icons 2.1.18 
Hydrogen 2.4.1 
hydrogen-launcher 1.2.2 
intentions 1.1.5 
language-latex 1.1.1 
latex 0.50.0 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
python-autopep8 0.1.3 
script 3.17.3 
sync-settings 0.8.6 
teletype 0.12.2 
todo-show 2.3.0 
```

**Comment by djh329** [comment]
I also had this error when reconfiguring `tabLength` through the projectSpecification settings (i.e. changed through a call to `Config.resetProjectSettings`

**Comment by TheMengzor** [comment]
Also affected that

**Comment by TheMengzor** [comment]
Disabled todo-show plugin and everything works fine

**Comment by UziTech** [comment]
if this is still an issue feel free to reopen
