### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by rsheldiii** [atom-community/sync-settings#433]
## Steps to reproduce:

1. install sync-settings and restore from backup
2. error occurs under multiple package install notifications, like editing-diff and goto-definition

I can provide my gist url if need be but it'll have to be expunged of sensitive data

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught TypeError: Cannot read property 'setEncoding' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:144

TypeError: Cannot read property 'setEncoding' of undefined
    at BufferedProcess.bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:144:17)
    at BufferedProcess.handleEvents (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:278:18)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:84:16)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:69:18)
    at PackageManager.module.exports.PackageManager.runCommand (/packages/sync-settings/lib/package-manager.coffee:30:5)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:182:6)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:180:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
  2x -3:57.8.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:49.4.0 core:confirm (input.hidden-input)
     -3:47.8.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:46.5.0 core:confirm (input.hidden-input)
  2x -3:40.9.0 core:backspace (input.hidden-input)
     -3:40.1.0 core:confirm (input.hidden-input)
     -3:34.2.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:33.5.0 core:confirm (input.hidden-input)
  2x -3:08.7.0 core:paste (input.hidden-input)
     -2:33.2.0 core:confirm (input.hidden-input)
  2x -2:21.9.0 core:save (input.hidden-input)
     -2:14.3.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:44.8.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:43.6.0 core:confirm (input.hidden-input)
     -0:37.7.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:16.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.2.0 
ask-stack 2.2.0 
busy-signal 1.4.3 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
language-openscad 0.4.3 
linter 2.2.0 
linter-coffeelint 2.0.0 
linter-eslint 8.4.1 
linter-rubocop 2.2.3 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
markdown-preview-plus 3.2.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
open-git-modified-files 0.2.4 
pain-split 1.4.0 
pigments 0.40.2 
prettier-atom 0.53.0 
pretty-json 2.0.0 
pristine-ui 1.1.11 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
if this is still an issue with the latest version feel free to reopen
