### ISSUE TITLE
Uncaught Error: Tried to unload active package 'tasks'

### ISSUE THREAD

**Issue by AlexWayfer** [atom-community/sync-settings#434]
[Enter steps to reproduce:]

1. Get "Your backup is out of date"
2. Choose "Restore"

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: linux 4.17.2-1-ARCH
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'tasks'

```
At /usr/lib/atom/src/package-manager.js:619

Error: Tried to unload active package 'tasks'
    at PackageManager.unloadPackage (/usr/lib/atom/src/package-manager.js:619:13)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at Object.installMissingPackages (/packages/sync-settings/lib/sync-settings.coffee:433:7)
    at /packages/sync-settings/lib/sync-settings.coffee:246:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:07.6.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.32.5 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-tabs 0.1.0 
atom-tabs-in-sidebar 1.1.0 
atom-typescript 12.5.3 
auto-detect-indentation 1.3.0 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
color-picker 2.3.0 
editorconfig 2.2.2 
file-icons 2.1.21 
genesis-ui 0.5.0 
git-time-machine 2.1.0 
go-plus 5.8.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
ide-crystal 0.3.3 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-crystal-actual 0.37.2 
language-fish-shell 1.1.0 
language-haml 0.31.1 
language-vue 0.23.1 
linter 2.2.0 
linter-erb 1.1.1 
linter-eslint 8.4.1 
linter-htmlhint 1.4.0 
linter-jshint 3.1.8 
linter-markdown 5.2.2 
linter-reek 2.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-spell 0.15.0 
linter-stylelint 4.3.0 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 2.0.0 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
platformio-ide-terminal 2.8.1 
precss 0.3.0 
remember-file-positions 0.2.3 
revert-buffer 0.6.0 
ruby-block 0.3.6 
ruby-block-converter 4.0.1 
ruby-define-method 0.2.2 
ruby-test 1.0.2 
seeing-is-believing 15.0.0 
seti-icons 1.5.4 
seti-ui 1.10.0 
single-click-open 0.2.2 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.5.2 
stacked-tabs 0.1.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
synced-sidebar 0.4.3 
tab-control 0.6.10 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
teletype 0.13.3 
term3 0.22.1 
toggle-quotes 1.1.0 
tree-view-open-files 0.3.0 
vertabs 1.1.1 
yard 0.5.1 
zentabs 0.8.9 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
