### ISSUE TITLE
Uncaught Error: Tried to unload active package 'teletype'

### ISSUE THREAD

**Issue by nattzkungz** [atom-community/sync-settings#435]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'teletype'

```
At C:\Users\daran\AppData\Local\atom\app-1.28.1\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'teletype'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.28.1/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (~/AppData/Local/atom/app-1.28.1/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.28.1/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
docker undefined 
emmet 2.4.3 
file-icons 2.1.21 
git-blame 1.7.0 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
intentions 1.1.5 
language-ini 1.20.0 
linter-gcc 0.7.1 
minimap 4.29.8 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
platomformio 0.7.1 
project-manager 3.3.6 
script 3.18.1 
sync-settings 0.8.6 
teletype 0.13.3 
tool-bar 1.1.7 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
