### ISSUE TITLE
Uncaught Error: Tried to unload active package 'sync-settings'

### ISSUE THREAD

**Issue by mcandre** [atom-community/sync-settings#439]
[Enter steps to reproduce:]

1. Try to use the Restore feature to apply settings to Atom.

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'sync-settings'

```
At C:\Users\a_pen\AppData\Local\atom\app-1.28.2\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'sync-settings'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.28.2/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (~/AppData/Local/atom/app-1.28.2/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.28.2/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -1:44.7.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-ui.theme-one-dark-syntax)
     -1:36.8.0 settings-view:open (div.tool-panel.tree-view)
```

### Non-Core Packages

```
busy-signal 1.4.3 
cucumber 0.6.0 
editorconfig 2.2.2 
intentions 1.1.5 
language-arm 1.2.3 
language-assembly 0.7.2 
language-awk 0.1.12 
language-batch 0.4.0 
language-brainfuck 0.2.0 
language-cmake 1.1.0 
language-coq 0.1.0 
language-d 3.3.0 
language-docker 1.1.8 
language-erlang 3.2.0 
language-fish-shell 1.1.0 
language-forth 0.2.3 
language-fortran 2.1.7 
language-fsharp 0.8.4 
language-generic-config 1.4.0 
language-gitignore 0.3.0 
language-groovy 0.7.0 
language-haskell 1.17.8 
language-ini 1.20.0 
language-latex 1.1.1 
language-lisp 0.2.0 
language-llvm 0.1.1 
language-lua 0.9.11 
language-matlab 0.2.1 
language-newlisp 0.1.0 
language-ocaml 1.9.5 
language-oz 0.1.0 
language-pascal 0.20.6 
language-pgsql 0.2.3 
language-powershell 4.0.1 
language-r 0.4.2 
language-rust 0.4.12 
language-scala 1.1.9 
language-scheme 1.4.0 
language-smalltalk 1.0.2 
language-sml 0.7.0 
language-swift 0.5.0 
language-tcl 0.1.2 
language-terraform 0.8.1 
language-vala 0.2.0 
language-viml 1.1.8 
language-x86 1.0.1 
language-x86-64-assembly 2.2.11 
linter 2.2.0 
linter-flake8 2.3.0 
minimap 4.29.8 
monokai 0.24.0 
monokai-shade 0.4.0 
release-notes 0.53.0 
shebang-set-grammar 0.8.0 
Stylus 3.1.1 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
