### ISSUE TITLE
Uncaught Error: Tried to unload active package 'snippets'

### ISSUE THREAD

**Issue by RFreij** [atom-community/sync-settings#441]
[Enter steps to reproduce:]

1. using this gist: https://gist.github.com/RFreij/fc3b9b83b52969d1256cd759a5cf188a
2. Using restore command

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'snippets'

```
At /usr/share/atom/resources/app/src/package-manager.js:630

Error: Tried to unload active package 'snippets'
    at PackageManager.unloadPackage (/usr/share/atom/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at Object.installMissingPackages (/packages/sync-settings/lib/sync-settings.coffee:433:7)
    at /packages/sync-settings/lib/sync-settings.coffee:246:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -6:38.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-phpunit 1.3.0 
atom-updater-linux 1.2.2 
docblockr 0.13.7 
editorconfig 2.2.2 
git-blame 1.7.0 
goto-definition 1.3.4 
minimap 4.29.8 
minimap-pigments 0.2.2 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
