### ISSUE TITLE
Uncaught Error: Tried to unload active package 'emmet'

### ISSUE THREAD

**Issue by moaali** [atom-community/sync-settings#443]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Ubuntu 16.04.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'emmet'

```
At /snap/atom/200/usr/share/atom/resources/app/src/package-manager.js:631

Error: Tried to unload active package 'emmet'
    at PackageManager.unloadPackage (/snap/atom/200/usr/share/atom/resources/app/src/package-manager.js:631:19)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at Object.installMissingPackages (/packages/sync-settings/lib/sync-settings.coffee:433:7)
    at /packages/sync-settings/lib/sync-settings.coffee:246:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:19.8.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-import-cost 1.2.0 
atom-jest-snippets 2.1.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.18.3 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
autocomplete-emojis 2.5.0 
autocomplete-modules 2.2.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.3.0 
copy-path 0.5.1 
docblockr 0.13.7 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.25 
git-plus 8.1.0 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.3 
language-babel 2.85.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-scss-lint 3.1.1 
linter-ui-default 1.7.1 
livestyle-atom 0.2.10 
lodash-snippets 2.0.0 
lorem 1.5.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.0 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
open-recent 5.0.0 
open-terminal-here 2.3.2 
pigments 0.40.2 
prettier-atom 0.55.2 
react-es7-snippets 0.3.13 
related 0.3.5 
sort-lines 0.18.0 
split-diff 1.5.2 
svg-preview 0.12.1 
sync-settings 0.8.6 
tab-foldername-index 3.3.0 
toggle-quotes 1.1.1 
tree-view-copy-relative-path 1.2.0 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
