### ISSUE TITLE
Uncaught Error: Tried to Restore the Backup from sync-settings and failed

### ISSUE THREAD

**Issue by moshesakajo** [atom-community/sync-settings#444]
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/~\.atom\config.cson'

Steps to reproduce:
1. Install sync-settings package
2. Backup all the settings and packages
3. Use Ctrl + Shift + P --> Sync Settings: Restore

Note: I removed the User folder and put "\<PrivateUserFolder\>" instead
Why is the following part of the path: "C:\Users\\\<PrivateUserFolder\>" included twice in the path to the .atom settings ?

Do you need the Gist contents ? If it is required than what is the way to do that without exposing the private details ?

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\<PrivateUserFolder>\.atom\C:\Users\<PrivateUserFolder>\.atom\config.cson'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'C:\Users\<PrivateUserFolder>\.atom\C:\Users\<PrivateUserFolder>\.atom\config.cson'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at /packages/sync-settings/lib/sync-settings.coffee:265:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -9:09.1.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -9:04.6.0 core:move-down (input.hidden-input)
     -9:03.2.0 core:confirm (input.hidden-input)
     -9:03.2.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:54.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -8:51.2.0 core:move-down (input.hidden-input)
     -8:50.1.0 core:confirm (input.hidden-input)
     -8:50.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:34.6.0 command-palette:toggle (div.panels-item)
  3x -1:29.5.0 core:move-down (input.hidden-input)
     -1:20.3.0 core:confirm (input.hidden-input)
     -1:20.3.0 sync-settings:view-backup (div.panels-item)
     -0:31.8.0 command-palette:toggle (div.panels-item)
     -0:22.4.0 sync-settings:restore (div.panels-item)
```

### Non-Core Packages

```
autocomplete-python 1.10.12 
file-icons 2.1.25 
highlight-selected 0.14.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
script 3.18.1 
sync-settings 0.8.6 
```

**Comment by moshesak** [comment]
I solved this problem by editing the path of the config.cson file. I only needed to remove the private path and leave config.cson
