### ISSUE TITLE
Uncaught Error: Tried to unload active package 'linter'

### ISSUE THREAD

**Issue by huynhminhnhan** [atom-community/sync-settings#454]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.1
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'linter'

```
At /private/var/folders/9z/r0dtfzh13lddncjssfx6b6_c0000gn/T/AppTranslocation/7D4661D5-9EDB-4AAF-A063-91429953A3D5/d/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Tried to unload active package 'linter'
    at PackageManager.unloadPackage (/private/var/folders/9z/r0dtfzh13lddncjssfx6b6_c0000gn/T/AppTranslocation/7D4661D5-9EDB-4AAF-A063-91429953A3D5/d/Atom.app/Contents/Resources/app/static/<embedded>:11:381493)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at o (/private/var/folders/9z/r0dtfzh13lddncjssfx6b6_c0000gn/T/AppTranslocation/7D4661D5-9EDB-4AAF-A063-91429953A3D5/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1032609)
    at ChildProcess.n.process.on.e (/private/var/folders/9z/r0dtfzh13lddncjssfx6b6_c0000gn/T/AppTranslocation/7D4661D5-9EDB-4AAF-A063-91429953A3D5/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1032815)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -5:03.1.0 core:copy (atom-notification.warning.icon.icon-alert.native-key-bindings.has-close.has-buttons)
     -3:58.3.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.8 
api-workbench 0.8.48 
ask-stack 2.2.0 
atom-clock 0.1.16 
atom-image-resize 0.3.0 
atom-import-js 0.21.0 
atom-material-syntax 1.0.8 
atom-pair 2.0.13 
atom-ternjs 0.18.3 
autocomplete-modules 2.2.6 
autocomplete-ruby 0.2.8 
bracket-padder 0.4.2 
busy-signal 2.0.0 
change-case 0.6.5 
code-peek 1.4.21 
color-picker 2.3.0 
comment 0.6.1 
copy-improved 0.0.4 
cucumber 0.7.0 
dash 1.7.1 
docs-snippets 0.8.0 
emmet 2.4.3 
erb-helper 1.1.0 
expose 0.15.0 
file-icons 2.1.29 
git-control 0.9.0 
git-plus 8.6.0 
git-time-machine 2.1.0 
goto-definition 1.3.4 
graphql-autocomplete 1.1.2 
hey-pane 1.1.2 
highlight-selected 0.14.0 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-refactor 0.7.1 
js-hyperclick 1.13.3 
jsformat 0.9.3 
jumpy 5.0.2 
language-babel 2.85.0 
language-docker 1.1.8 
language-dotenv 1.2.0 
language-ejs 0.4.0 
language-graphql 1.0.0 
language-groovy 0.7.0 
language-haml 0.32.1 
language-ini 1.20.0 
language-javascript-jsx 0.3.7 
language-json5 1.1.1 
language-lua 0.9.11 
language-luajit 1.2.0 
language-postcss 1.3.1 
language-r 0.4.2 
language-scala 1.1.9 
language-slim 1.0.0 
linter 2.3.0 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
