### ISSUE TITLE
Uncaught Error: Tried to unload active package 'linter-ui-default'

### ISSUE THREAD

**Issue by pavelkukov** [atom-community/sync-settings#455]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'linter-ui-default'

```
At C:\Users\PC\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

Error: Tried to unload active package 'linter-ui-default'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381493)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -1:43.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-easy-jsdoc 4.12.5 
auto-indent 0.5.0 
autocomplete-javascript 0.0.2 
autocomplete-jsdoc 0.0.2 
busy-signal 1.4.3 
editor-settings 1.1.3 
editorconfig 2.2.2 
eslint-fixer 1.3.0 
expose 0.15.0 
fast-eslint 4.9.0 
fold-comments 0.6.0 
fold-functions 0.11.0 
git-blame 1.8.0 
intentions 1.1.5 
jscs-fixer 1.3.0 
jsdoc-generator 0.2.5 
jsdoc-preview 1.2.1 
language-babel 2.85.0 
language-demandware 0.1.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-standard 6.1.0 
linter-jscs 4.1.3 
linter-jshint 3.1.9 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
split-diff 1.5.3 
styled-components-snippets 0.6.1 
sync-settings 0.8.6 
vertical-tabs 1.0.7 
xml-formatter 0.11.0 
```

**Comment by UziTech** [comment]
should be fixed by v2.0.0
