### ISSUE TITLE
Uncaught Error: Tried to unload active package 'scroll-marker'

### ISSUE THREAD

**Issue by rashtay** [atom-community/sync-settings#457]
**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'scroll-marker'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Tried to unload active package 'scroll-marker'
    at PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380394)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at /packages/sync-settings/lib/sync-settings.coffee:420:13
    at /packages/sync-settings/lib/sync-settings.coffee:444:7
    at /packages/sync-settings/lib/package-manager.coffee:171:9
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1127206)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1127294)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125962)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
     -3:11.3.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:01.0 core:paste (input.hidden-input)
     -1:31.2.0 sync-settings:restore (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-ide-ui 0.13.0 
atom-material-ui 2.1.3 
atom-react-native-style 0.2.0 
atom-wrap-in-tag 0.6.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-modules 2.2.6 
busy-signal 2.0.0 
clipboard-plus 0.5.1 
dash-syntax 0.4.2 
dash-ui 0.4.4 
docblockr 0.13.7 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.29 
highlight-line 0.12.0 
highlight-selected 0.14.0 
ide-flowtype 0.24.0 
intentions 1.1.5 
js-hyperclick 1.17.0 
language-babel 2.85.0 
linter 2.0.0 
linter-eslint 8.5.2 
linter-ui-default 1.7.1 
local-history 4.3.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pigments 0.40.2 
scroll-marker 0.3.2 
styri-syntax 1.0.0 
sync-settings 0.8.6 
tree-view-copy-relative-path 1.2.0 
```

**Comment by UziTech** [comment]
this should be fixed in v2.0.0
