### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type function

### ISSUE THREAD

**Issue by eristoddle** [atom-community/sync-settings#458]
Steps to reproduce:

1. Just trying to restore the settings

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught The "path" argument must be of type string. Received type function

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at PackageManager.resolvePackagePath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:373919)
    at Object._getAvailablePackageMetadataWithoutDuplicates (/packages/sync-settings/lib/sync-settings.coffee:205:32)
    at Object.getPackages (/packages/sync-settings/lib/sync-settings.coffee:192:5)
    at Object.installMissingPackages (/packages/sync-settings/lib/sync-settings.coffee:385:27)
    at /packages/sync-settings/lib/sync-settings.coffee:246:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -0:05.6.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-vivid-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
academic-markdown 0.3.8 
android-debugger 0.1.0 
ariake-dark-syntax 0.1.3 
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-beautify 0.33.4 
atom-dark-monokai-syntax 0.18.0 
atom-diary 1.2.1 
atom-focus-mode 1.0.0 
atom-hemingway 0.3.2 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-maven 1.3.2 
atom-notes 1.20.0 
atom-ternjs 0.19.1 
atom-typescript 13.2.1 
atom-writing-env 0.1.3 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-asciidoc 0.1.2 
autocomplete-bibtex 1.2.7 
autocomplete-html-entities 0.2.0 
autocomplete-solidity 0.3.4 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
copy-path 0.5.1 
dark-one-dark-syntax 2.3.0 
dark-plus-syntax 2.5.0 
docblockr 0.13.7 
editor-settings 1.1.3 
editorconfig 2.5.0 
es6-javascript 1.0.0 
file-icons 2.1.33 
file-types 1.0.1 
fold-search-results 1.0.5 
ghar-dark-syntax 2.0.0 
git-blame 1.8.0 
git-plus 8.7.1 
git-plus-plus 1.1.0 
gl-dark-syntax 3.0.0 
glacier-dark-ui 1.5.0 
go-debug 1.6.2 
go-plus 6.1.0 
googlesearch 1.5.0 
grunt-snippets 0.1.1 
highlight-selected 0.16.0 
Hydrogen 2.10.3 
ide-go 0.12.3 
ide-java 0.9.0 
ide-php 0.7.18 
ide-typescript 0.9.1 
imdone-atom-github 0.1.11 
intentions 1.1.5 
javascript-snippets 1.2.1 
jekyll 2.1.0 
language-apache 1.8.0 
language-asciidoc 1.11.0 
language-aspx 0.5.0 
language-docker 1.1.8 
language-ethereum 0.3.9 
language-javascript-jsx 0.3.7 
language-liquid 0.7.0 
language-markdown 0.37.0 
language-solidity 0.1.1 
leanpub-snippets 0.2.0 
linter 2.3.0 
linter-alex 6.0.2 
linter-eslint 8.5.5 
linter-golinter 1.3.0 
linter-google-styleguide 1.0.0 
linter-just-say-no 0.7.5 
linter-retextjs 0.31.0 
linter-solidity 0.5.0 
linter-spell 0.15.0 
linter-stylelint 4.4.9 
linter-swagger 0.6.1 
linter-ui-default 1.7.1 
linter-ui-plus 0.3.2 
linter-write-good 0.9.2 
local-history 4.3.1 
mac-os-ui 0.3.0 
markdown-helpers 0.3.0 
markdown-pdf 2.2.0 
markdown-preview-plus 3.9.0 
markdown-writer 2.11.7 
merge-conflicts 1.4.5 
multirow-tabs 0.3.3 
native-ui 0.27.0 
neutron-dark-ui 2.1.4 
npm-plus 0.4.0 
one-dark-shade-ui 0.1.0 
one-dark-vivid-syntax 1.8.1 
open-file 1.4.0 
pear-dark-syntax 1.0.9 
pigments 0.40.2 
pinned-tabs 2.1.1 
prettier-atom 0.57.2 
project-manager 3.3.7 
prompt-big-file 0.5.0 
react 0.18.0 
react-snippets 1.1.3 
smart-tags 0.1.5 
snow-dark-syntax 0.1.1 
sort-lines 0.19.0 
spectrum-dark-syntax 0.2.0 
split-diff 1.6.0 
spring-dark-syntax 0.0.4 
sync-settings 0.8.6 
TabNine 0.1.5 
thesaurus 0.3.0 
titan-dark-syntax 2.0.0 
todo-show 2.3.2 
tool-bar 1.1.12 
tool-bar-almighty 0.9.0 
tool-bar-markdown-writer 0.5.0 
two-dark-ui 1.0.2 
typewriter 0.8.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
Warm-Dark-syntax 0.1.0 
wordcount 3.1.0 
Zen 0.18.0 
zhk-dark-syntax 0.3.1 
```

**Comment by eristoddle** [comment]
Somehow by disabling and uninstalling packages, I managed to fix this. I tried so many things, I am not quite sure what did it.

**Comment by seannowotny** [comment]
What fixed it for me was disabling all community packages, restarting Atom and re-enabling all of them except for "elm-navigator", which seems to have caused this error.
