### ISSUE TITLE
Uncaught Error: Tried to unload active package 'atom-ide-datatip'

### ISSUE THREAD

**Issue by accu-joeykarns** [atom-community/sync-settings#459]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: Tried to unload active package 'atom-ide-datatip'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Tried to unload active package 'atom-ide-datatip'
    at PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381067)
    at PackageManager.module.exports.PackageManager.install (/packages/sync-settings/lib/package-manager.coffee:158:19)
    at Object.installPackage (/packages/sync-settings/lib/sync-settings.coffee:439:20)
    at /packages/sync-settings/lib/sync-settings.coffee:410:12
    at /packages/sync-settings/lib/sync-settings.coffee:409:9
    at Object.installMissingPackages (/packages/sync-settings/lib/sync-settings.coffee:433:7)
    at /packages/sync-settings/lib/sync-settings.coffee:246:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -0:58.5.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:31.8.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
build-gradle 0.6.0 
busy-signal 2.0.1 
docker 0.8.0 
ide-docker 0.1.0 
ide-json 0.2.1 
ide-yaml 0.5.1 
intentions 1.1.5 
language-docker 1.1.8 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-kotlin 0.5.0 
linter 2.3.1 
linter-docker 0.3.2 
linter-js-yaml 1.4.6 
linter-jsonlint 1.4.0 
linter-kotlin 0.6.0 
linter-packer-validate 1.2.0 
linter-ui-default 1.8.0 
pretty-json 2.1.2 
project-manager 3.3.7 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
This should be fixed in v2.0.0
