### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open '$ATOM_HOME/init.coffee'

### ISSUE THREAD

**Issue by Stargrazer82301** [atom-community/sync-settings#460]
[[Enter steps to reproduce:]

1. Install snyc-settings on one machine, and use to make backup to gist
2. Install sync settings on different machine, and attempt to restore that backup
3. This crash appears

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.6

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Chris\.atom/init.coffee'

```
At fs.js:143

Error: EPERM: operation not permitted, open 'C:\Users\Chris\.atom/init.coffee'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1321:33)
    at /packages/sync-settings/lib/sync-settings.coffee:257:16
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -3:15.8.0 core:paste (input.hidden-input)
     -3:14.8.0 core:select-all (input.hidden-input)
     -3:13.9.0 core:backspace (input.hidden-input)
  2x -2:37 core:paste (input.hidden-input)
     -2:01.2.0 sync-settings:restore (div.package-detail)
```

### Non-Core Packages

```
Hydrogen 2.12.0 
hydrogen-python 0.0.8 
sync-settings 0.8.6 
```

**Comment by UziTech** [comment]
is this still an issue? or did you figure out what was wrong?

**Comment by UziTech** [comment]
If this is still an issue feel free to reopen it
