### ISSUE TITLE
Failed to load the sync-settings package > Unexpected token ...

### ISSUE THREAD

**Issue by rdevroede** [atom-community/sync-settings#486]
**Describe the bug**
I updated from v0.8.6 to v2.3.0 and since then I get a Stack Trace:

```
SyntaxError: Unexpected token ...
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/opt/atom/resources/app/src/package.js:782:33)
    at measure (/opt/atom/resources/app/src/package.js:143:22)
    at Package.measure (/opt/atom/resources/app/src/package.js:88:25)
    at Package.load (/opt/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/opt/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/opt/atom/resources/app/src/package-manager.js:531:20)
    at Config.transact (/opt/atom/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/opt/atom/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/opt/atom/resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

Atom then reports: "The error was thrown from the sync-settings package. This issue has already been reported." and references https://github.com/atom-community/sync-settings/issues/211

Updating to the latest version (v2.3.1) did not solve the issue.

**To Reproduce**
It happens every start when trying to load the module.

**Expected behavior**
Sync my settings.

**Screenshots**
N/A

**Versions**
 - OS: Linux Mint 19.3 Tricia
 - Atom: 
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
 - APM:
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.17
git 2.17.1

**Additional context**
N/A

**Comment by UziTech** [comment]
Could you try updating Atom? Uninstalling and reinstalling sync settings seems to be the fix in the linked issue.

**Comment by rdevroede** [comment]
I tried the fix of the linked issue first. Forgot to mention that. Uninstalling and reinstalling sync settings did not solve it.

I am however running it on another node now and there it works properly.

- OS: Debian 9.12
- Atom:
Atom : 1.44.0
Electron: 4.2.7
Chrome : 69.0.3497.128
Node : 10.11.0
- APM:
apm 2.4.3
npm 6.2.0
node 10.2.1 x64
atom 1.44.0
python 2.7.13
git 2.11.0

I will try updating Atom on my other node tomorrow.

**Comment by rdevroede** [comment]
Updating Atom fixed it. I was using "ppa:webupd8team/atom" which stopped at 1.26.1. Now using https://packagecloud.io/AtomEditor/atom, which installed 1.44.0.
