### ISSUE TITLE
Potential conflict with DocBlock Package

### ISSUE THREAD

**Issue by Tokariew** [atom-community/sync-settings#488]
**Describe the bug**
Potential conflict with DocBlock-python package

**To Reproduce**
1. Install  DocBlock-python package
2. Install sync-settings
3. Atom crash and display message 

> The editor has crashed

After that is not possible to run atom without crashing editor immediately after lunching. 
**Expected behavior**

Not crash after installing this package

**Screenshots**

**Versions**
 - OS: Windows 10 1909 
 - Atom: 
 Atom    : 1.44.0          
Electron: 4.2.7            
Chrome  : 69.0.3497.128    
Node    : 10.11.0          

 - APM: 

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python 3.7.4
git 2.25.0.windows.1
visual studio

**Additional context**

It seems that atom crash when trying to display notification that package is not configured for sync

DocBlock can be disabled and atom will crash after installing sync-settings package. But later will run fine.

I don't now if this log is usefull

```
C:\Users\tokariew\.atom\packages\sync-settings\lib\notify.js:79 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.addNotificationView (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:221192)
    at C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:217303
    at Function.simpleDispatch (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1212986)
    at Emitter.emit (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1214427)
    at NotificationManager.addNotification (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:326934)
    at NotificationManager.addError (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:326712)
    at Object.missingMandatorySettings (C:\Users\tokariew\.atom\packages\sync-settings\lib\notify.js:79:29)
    at Object.checkMandatorySettings (C:\Users\tokariew\.atom\packages\sync-settings\lib\sync-settings.js:117:11)
    at Immediate.setImmediate (C:\Users\tokariew\.atom\packages\sync-settings\lib\sync-settings.js:53:42)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by UziTech** [comment]
The error `Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'` looks like the error is coming from displaying the notification not sending the notification.

What other packages do you have installed?

**Comment by Tokariew** [comment]
I can run this with only dockblock-python and sync-settings and atom will still crash for me

but full list of installed packages

```
atom-beautify
atom-clock
atom-isort
autocomplete-python
busy-signal
docblock-python
file-icons
highlight-selected
intentions
language-kivy
language-latex
language-matlab
latex
latex-friend
latextools
linter
linter-flake8
linter-pydocstyle
linter-ui-default
markdown-preview-plus
minimap
minimap-highlight-selected
minimap-linter
minimap-pigments
monokai-seti
pdf-view
pigments
python-autopep8
script
seti-ui
sync-settings

```

**Comment by UziTech** [comment]
uninstall sync-settings package, open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>), run the following command, and tell me what happens.

```js
var n = atom.notifications.addError('sync-settings test', {
	dismissable: true,
	buttons: [{
		text: 'Package settings',
		onDidClick () {
			atom.workspace.open('atom://config/packages/sync-settings')
			n.dismiss()
		},
	}],
})
```

**Comment by Tokariew** [comment]
i got this error message, but atom didn't crash

```
<embedded>:11 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.addNotificationView (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:221192)
    at C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:217303
    at Function.simpleDispatch (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1212986)
    at Emitter.emit (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:1214427)
    at NotificationManager.addNotification (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:326934)
    at NotificationManager.addError (C:\Users\tokariew\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:326712)
    at <anonymous>:1:28
```

**Comment by UziTech** [comment]
it seems like `docblock-python` might conflict with the [`notifications`](https://atom.io/packages/notifications) package.

**Comment by Tokariew** [comment]
ok, I will open issue about it in docblock-python repository. Thank you for the help.

**Comment by UziTech** [comment]
No problem, thanks for taking the time to report it.
