### ISSUE TITLE
Errors about Multiple Location Services

### ISSUE THREAD

**Issue by wizard04wsu** [atom-community/sync-settings#625]
**Describe the bug**

When I open Atom, I'm shown this error for a few seconds:

> Sync-Settings: Error parsing the file 'packages.json'. (SyntaxError: Unexpected string in JSON at position 1491)

If I uninstall and reinstall the package, I see that error, plus two more referencing "Sync-Settings: Multiple Location Services". Screenshot below. The "View Issue" button goes to #333.

**To Reproduce**
1. Open Atom
2. The first error is shown, then disappears
3. Click on File-->Settings-->Packages-->sync-settings
4. Click Uninstall
5. Click Install
6. All three errors are shown, then the first (bottom) one disappears

**Expected behavior**
There should be no error messages

**Screenshots**
![sync-settings errors](https://user-images.githubusercontent.com/695638/104813015-612db200-57d4-11eb-883f-83ab8bf599af.PNG)

**Versions**
 - OS: Windows 10 Pro, version 2004
 - Atom: 
Atom: 1.54.0
Electron: 6.1.12
Chrome: 76.0.3809.146
Node: 12.4.0

 - APM: 
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 3.7.0
git 2.22.0.windows.1
visual studio

**Additional context**

Stack trace:
> Error: Sync-Settings: Multiple Location Services\
    at Object.syncSettingslocationService (C:\Users\Andy\.atom\packages\sync-settings\lib\main.js:71:10)\
    at Provider.provide (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:1093689)\
    at ServiceHub.consume (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3653929)\
    at Package.activateServices (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3662214)\
    at Package.activateNow (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3658969)\
    at C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3658293\
    at Package.measure (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3655871)\
    at C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3658153\
    at new Promise (<anonymous>)\
    at Package.activate (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:3658096)\
    at PackageManager.activatePackage (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:383646)\
    at C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:916751
    at r (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:11:911357)
    at s (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:1121307)
    at ChildProcess.<anonymous> (C:\Users\Andy\AppData\Local\atom\app-1.54.0\resources\app\static\<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by UziTech** [comment]
Do you have sync-settings-git-location or sync-settings-git-location installed?

**Comment by wizard04wsu** [comment]
sync-settings-folder-location is installed

**Comment by UziTech** [comment]
I just released a version that should log the error in the console instead of throwing when multiple location services are installed. Try v5.2.1 and see if it fixes the issue.

Can you share a list of installed packages?

**Comment by wizard04wsu** [comment]
Sorry for the late response. v5.2.1 resolves the "failed to activate..." error, but the other two messages still display if the sync-settings-folder-location package is also enabled.

Installed (enabled) packages:
javascript-regex
language-gcode-fff
language-powershell
language-reg
remember-folds
sync-settings
sync-settings-folder-location

**Comment by UziTech** [comment]
The `Error parsing the file 'packages.json'` error is saying that the `packages.json` file in your backup folder is invalid json. Could you share that file?

**Comment by UziTech** [comment]
For the `Multiple Location Services` error can you run the following code in your console on Atom and paste the output into a comment?

1. Open Atom
2. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>
3. run the following code in the console:
   ```
   atom.packages.serviceHub.providers
     .filter(s => s.servicesByVersion["1.0.0"] && "sync-settings-location" in s.servicesByVersion["1.0.0"])
     .map(s => s.servicesByVersion["1.0.0"]["sync-settings-location"].create.toString())
   ```

**Comment by wizard04wsu** [comment]
`packages.json` is attached as a text file.
[packages.json.txt](https://github.com/atom-community/sync-settings/files/5861428/packages.json.txt)

Console output:
`["async create () {↵		let folderPath↵		try {↵			fold…up', () => this.create(), folderPath)↵			}↵		}↵	}"]`

**Comment by UziTech** [comment]
looks like your package.json is invalid

```json
	"dumb-quoter": {
		"version": "0.1.0"
	"docblockr": {
		"version": "0.13.7"
	},
```

if you add `},` after `"version": "0.1.0"` it should fix it.

**Comment by UziTech** [comment]
As far as the `Multiple Location Services` error I don't know why Atom is consuming the service twice but you should be able ignore the error because it will still work. Maybe I will add a setting to prevent the error.

**Comment by wizard04wsu** [comment]
That worked! I'm not getting any errors now.

**Comment by UziTech** [comment]
Glad we could get that figured out!
